remove trimmer.sh and other clutter. just run the tests for now to see if it works

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -487,33 +487,30 @@ jobs:
         run: mvn clean install -DskipTests -Pdistribution
 
       - name: Run Quarkus Integration Tests
-        run: |
-          mvn clean install -nsu -B -f quarkus/tests/pom.xml | misc/log/trimmer.sh
-          TEST_RESULT=${PIPESTATUS[0]}
-          find . -path '*/target/surefire-reports/*.xml' | zip -q reports-quarkus-tests.zip -@
-          exit $TEST_RESULT
+        run: mvn clean install -nsu -B -f quarkus/tests/pom.xml
+          # TEST_RESULT=${PIPESTATUS[0]}
+          # find . -path '*/target/surefire-reports/*.xml' | zip -q reports-quarkus-tests.zip -@
+          # exit $TEST_RESULT
 
       - name: Run Quarkus Storage Tests
-        run: |
-          mvn clean install -nsu -B -f quarkus/tests/pom.xml -Ptest-database -Dtest=PostgreSQLStartDatabaseTest | misc/log/trimmer.sh
-          TEST_RESULT=${PIPESTATUS[0]}
-          find . -path '*/target/surefire-reports/*.xml' | zip -q reports-quarkus-tests.zip -@
-          exit $TEST_RESULT
+        run: mvn clean install -nsu -B -f quarkus/tests/pom.xml -Ptest-database -Dtest=PostgreSQLStartDatabaseTest
+          # TEST_RESULT=${PIPESTATUS[0]}
+          # find . -path '*/target/surefire-reports/*.xml' | zip -q reports-quarkus-tests.zip -@
+          # exit $TEST_RESULT
 
       - name: Run Quarkus Tests in Docker
-        run: |
-          mvn clean install -nsu -B -f quarkus/tests/pom.xml -Dkc.quarkus.tests.dist=docker | misc/log/trimmer.sh
-          TEST_RESULT=${PIPESTATUS[0]}
-          exit $TEST_RESULT
+        run: mvn clean install -nsu -B -f quarkus/tests/pom.xml -Dkc.quarkus.tests.dist=docker
+          # TEST_RESULT=${PIPESTATUS[0]}
+          # exit $TEST_RESULT
 
-      - name: Quarkus test reports
-        uses: actions/upload-artifact@v3
-        if: failure()
-        with:
-          name: reports-quarkus-tests
-          retention-days: 14
-          path: reports-quarkus-tests.zip
-          if-no-files-found: ignore
+#      - name: Quarkus test reports
+#        uses: actions/upload-artifact@v3
+#        if: failure()
+#        with:
+#          name: reports-quarkus-tests
+#          retention-days: 14
+#          path: reports-quarkus-tests.zip
+#          if-no-files-found: ignore
 
 #  quickstarts-tests:
 #    name: Quickstarts Tests
